### ISSUE TITLE
Middle screw holes should be moved

### ISSUE THREAD

**Issue by BenRoe** [yiancar/gingham_pcb#1]
Hi,
first thanks for making this beautiful keyboard open source.
I assembled the keyboard and found that the top middle screw, is colliding with a switch.
![IMG_6327](https://user-images.githubusercontent.com/643834/62303627-c7a5ff80-b47c-11e9-9cc3-1aa4b530f1ba.jpg)

The bottom middle screw is direct under the space stabilizer wire. It works ok.
![IMG_6328](https://user-images.githubusercontent.com/643834/62304088-9843c280-b47d-11e9-8a12-7cd100c764fa.jpg)

I guess it is enough if you move one screw hole to the arrow position and remove the second.
<img width="1041" alt="Bildschirmfoto 2019-08-01 um 16 56 03" src="https://user-images.githubusercontent.com/643834/62304231-e062e500-b47d-11e9-91cf-3c93aef1978a.png">

**Comment by yiancar** [comment]
Hello Ben, I think the best solution would be to move H9 a bit further up and H10 a bit further down

**Comment by BenRoe** [comment]
That seems the easiest solution.
Are you doing it? I could create a PR this weekend.

**Comment by yiancar** [comment]
I moved both the mounts. top one went a bit further up to clear the 3 switches.
Bottom one went further down in the spacebar area.

https://github.com/yiancar/gingham_pcb/commit/b1900f6dbd8959f06bac23ca52f8e2e1b224f5ad

**Comment by BenRoe** [comment]
Should work.
Thank you for doing it and keep working on new keyboards.
