### ISSUE TITLE
Keyboard on iso abnt2 format

### ISSUE THREAD

**Issue by luizcorreia** [yiancar/gingham_pcb#2]
It's possible make your awesome keyboard work with the abnt2 brazilian format?

![900px-kb_portuguese_brazilsvg_](https://user-images.githubusercontent.com/474856/68542446-5c2cd180-038b-11ea-8235-85b70dc24862.png)

**Comment by yiancar** [comment]
Hello! Sorry Just saw this:)

My design aesthetic calls against making it a "swiss cheese" PCB. As a result I will not be modifying the bottom row to anything other that what it currently is.

Saying this, the design is opensource so you can go ahead and make your own!

Thanks for taking a look !
